### ISSUE TITLE
Members update task failure

### ISSUE THREAD

**Issue by tyler274** [evecm/ecm#14] opened 2015-01-20 02:10 UTC
2015-01-20 01:50:17,887 [INFO ] ecm.apps.hr.tasks.members.tracking - fetching /corp/MemberTracking.xml.aspx...
2015-01-20 01:50:39,508 [INFO ] ecm.apps.hr.tasks.members.tracking - 1075 members parsed, 1 changes since last scan
2015-01-20 01:50:49,049 [INFO ] ecm.apps.hr.tasks.members.security - fetching /corp/MemberSecurity.xml.aspx...
2015-01-20 01:51:06,253 [ERROR] ecm.apps.scheduler.models -
Traceback (most recent call last):
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(**args)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/apps/hr/tasks/members/__init__.py", line 26, in update
    security.update()
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/apps/hr/tasks/members/security.py", line 90, in update
    titleDiffs = storeTitles(oldTitles, newTitles, currentTime)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/ecm/apps/hr/tasks/members/security.py", line 207, in storeTitles
    d.save()
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 943, in execute_sql
    cursor.execute(sql, params)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
  File "/home/bovril/ecm2/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
Warning: Field 'id' doesn't have a default value

Shows in ecm.log on member update

**Comment by ggrog** [comment] 2015-01-20 15:40
I haven't seen this one - but as a warning it may be benign.  Is the warning recurring or is it just a one time thing?

(hint - ECM throws a lot of ignorable errors)

**Comment by tyler274** [comment] 2015-01-20 16:41
It is a recurring error yes.

**Comment by tyler274** [comment] 2015-01-26 18:03
On every 2 hour member update the error triggers, been consistent for the last week, causes the member update to fail.

**Comment by ggrog** [comment] 2015-02-04 04:43
I haven't forgotten about this; I don't know the root cause so I will have to patch around it, unfortunately.  I should have something for you in a few days.

**Comment by tyler274** [comment] 2015-02-05 03:48
:+1: Awesome

**Comment by Dharr-Guartonzec** [comment] 2015-09-10 12:58
I have the same issue. I can fix this with deleting all members and polling them again, but obviously the error is coming back every now and then. From what i believe it is as soon as a new member joins corp.

**Comment by ggrog** [comment] 2015-09-10 15:20
Dharr, can you enable debug logging?  In your instance settings.py file, in the `# LOGGING #`
section, look for the line `'level': 'INFO',` under file_handler, change that to `'level': 'DEBUG',`.

Then next time the task fails please send me the relevant section of ecm.log.  (It will start with "fetching /corp/MemberSecurity.xml.aspx...")

**Comment by Dharr-Guartonzec** [comment] 2015-09-10 15:50
Looks like it is already set to DEBUG, right ?

'loggers': {
        'ecm': {                                        # remove console handler on production
            'handlers': ['file_handler', 'email_handler', 'console_handler'],
            'propagate': True,
            'level': 'DEBUG',
        },
        'django.request': {
            'handlers': ['email_handler', 'error_file_handler', 'file_handler'],
            'propagate': False,
            'level': 'ERROR',
        },
    }

**Comment by ggrog** [comment] 2015-09-10 16:38
Yes, you should then have some more information available in the ecm.log file.  I don't think the trace logs go there however so you'll have to match up the timestamp failed task with the debug info in the ecm.log.

**Comment by ggrog** [comment] 2015-09-10 18:59
Wait, sorry, look a few lines down from the line `'file_handler': {` (Line 273 on a default settings.py file.)

**Comment by Dharr-Guartonzec** [comment] 2015-09-11 10:52
Done. Also probably tonight another member will join corp, we will see.

 268     },
    269     'handlers': {
    270         'file_handler': {
    271             'class': 'logging.handlers.TimedRotatingFileHandler',
    272             'formatter': 'ecm_formatter',
    273             'level': 'DEBUG',

**Comment by Dharr-Guartonzec** [comment] 2015-09-14 09:37
I Had a busy weekend, but a new member joined and we have the error again. Also a new POS got setup and causes now also errors.

Now where to look at the errors? In ecm.log the day the errors first happened again?

**Comment by Dharr-Guartonzec** [comment] 2015-09-14 09:41
I accidently re-run the UTF8 converting script, and after that the POS error was gone. Seems still content is written into the DB in non UTF8 format... weird.... But on the members issue this did not help.

**Comment by Dharr-Guartonzec** [comment] 2015-09-14 09:58
Doh, i haven't set UFT8 in the my.cnf file... I corrected this now and we will see if on the next changes another error will occur.

**Comment by ggrog** [comment] 2015-09-14 16:25
Do you have lines above the stack dump of the form: `2015-09-14 04:xx:xx,xxx [DEBUG]`?  Did you restart your webserver instance after enabling debug? :)

**Comment by Dharr-Guartonzec** [comment] 2015-09-14 16:50
Doh, i have not restarted the webserver, lol.... done it now, so i will add a new member later tonight when i'm at home and we will see what happens.

**Comment by vanderheyde** [comment] 2015-09-14 19:26
2015-09-14 21:22:40,400 [INFO ] ecm.plugins.industry.views - Initialized item groups (took 0.16 sec.)
2015-09-14 21:23:13,090 [INFO ] ecm.apps.hr.tasks.members.tracking - fetching /corp/MemberTracking.xml.aspx...
2015-09-14 21:23:13,271 [DEBUG] ecm.apps.hr.tasks.members.tracking - current time : 2015-09-14 19:23:12+00:00
2015-09-14 21:23:13,271 [DEBUG] ecm.apps.hr.tasks.members.tracking - cached util : 2015-09-14 20:34:36+00:00
2015-09-14 21:23:13,271 [DEBUG] ecm.apps.hr.tasks.members.tracking - parsing api response...
2015-09-14 21:23:13,330 [DEBUG] ecm.apps.hr.tasks.members.tracking - RESIGNED MEMBERS:
2015-09-14 21:23:13,330 [DEBUG] ecm.apps.hr.tasks.members.tracking - (none)
2015-09-14 21:23:13,330 [DEBUG] ecm.apps.hr.tasks.members.tracking - NEW MEMBERS:
2015-09-14 21:23:13,330 [DEBUG] ecm.apps.hr.tasks.members.tracking - (none)
2015-09-14 21:23:13,330 [INFO ] ecm.apps.hr.tasks.members.tracking - 10 members parsed, 0 changes since last scan
2015-09-14 21:23:13,375 [INFO ] ecm.apps.hr.tasks.members.security - fetching /corp/MemberSecurity.xml.aspx...
2015-09-14 21:23:13,560 [DEBUG] ecm.apps.hr.tasks.members.security - current time : 2015-09-14 19:23:12+00:00
2015-09-14 21:23:13,561 [DEBUG] ecm.apps.hr.tasks.members.security - cached util : 2015-09-14 20:20:12+00:00
2015-09-14 21:23:13,561 [DEBUG] ecm.apps.hr.tasks.members.security - parsing api response...
2015-09-14 21:23:13,586 [ERROR] ecm.apps.scheduler.models -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(**args)
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/members/__init__.py", line 26, in update
    security.update()
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/members/security.py", line 84, in update
    newTitles.update(parseOneMemberTitles(member, my_corp))
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/members/security.py", line 122, in parseOneMemberTitles
    title = Title.objects.get(corp=my_corp, titleID=t.titleID)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: Title matching query does not exist.

**Comment by ggrog** [comment] 2015-09-15 05:09
Ok - I was able to reproduce the error `DoesNotExist: Title matching query does not exist` and posted a fix.  Please try it out with `pip install git+https://github.com/evecm/ecm --upgrade`.  I don't know that it will fix the `Warning: Field 'id' doesn't have a default value` error.  Still looking for a [DEBUG] dump of that one.

**Comment by vanderheyde** [comment] 2015-09-15 06:03
I've done the upgrade but to no avail:

2015-09-15 07:50:47,871 [INFO ] ecm.apps.hr.tasks.members.tracking - fetching /corp/MemberTracking.xml.aspx...
2015-09-15 07:50:48,078 [DEBUG] ecm.apps.hr.tasks.members.tracking - current time : 2015-09-15 05:50:46+00:00
2015-09-15 07:50:48,078 [DEBUG] ecm.apps.hr.tasks.members.tracking - cached util : 2015-09-15 11:47:46+00:00
2015-09-15 07:50:48,078 [DEBUG] ecm.apps.hr.tasks.members.tracking - parsing api response...
2015-09-15 07:50:48,151 [DEBUG] ecm.apps.hr.tasks.members.tracking - RESIGNED MEMBERS:
2015-09-15 07:50:48,151 [DEBUG] ecm.apps.hr.tasks.members.tracking - (none)
2015-09-15 07:50:48,151 [DEBUG] ecm.apps.hr.tasks.members.tracking - NEW MEMBERS:
2015-09-15 07:50:48,151 [DEBUG] ecm.apps.hr.tasks.members.tracking - (none)
2015-09-15 07:50:48,152 [INFO ] ecm.apps.hr.tasks.members.tracking - 10 members parsed, 0 changes since last scan
2015-09-15 07:50:48,213 [INFO ] ecm.apps.hr.tasks.members.security - fetching /corp/MemberSecurity.xml.aspx...
2015-09-15 07:50:48,400 [DEBUG] ecm.apps.hr.tasks.members.security - current time : 2015-09-15 05:50:46+00:00
2015-09-15 07:50:48,401 [DEBUG] ecm.apps.hr.tasks.members.security - cached util : 2015-09-15 06:47:46+00:00
2015-09-15 07:50:48,401 [DEBUG] ecm.apps.hr.tasks.members.security - parsing api response...
2015-09-15 07:50:48,422 [ERROR] ecm.apps.scheduler.models -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(**args)
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/members/__init__.py", line 26, in update
    security.update()
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/members/security.py", line 84, in update
    newTitles.update(parseOneMemberTitles(member, my_corp))
  File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/members/security.py", line 122, in parseOneMemberTitles
    title = Title.objects.get(corp=my_corp, titleID=t.titleID)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
    self.model._meta.object_name)
DoesNotExist: Title matching query does not exist.

**Comment by ggrog** [comment] 2015-09-15 06:15
That error is from the previous version.  Make sure you're restarted your web server instance, or something went wrong with the install.  Also, run the titles task first.

**Comment by Dharr-Guartonzec** [comment] 2015-09-15 09:10
Morning, hope you enjoyed the summer break grogg. :) 

I have today a new error with "corp assets" and some Debug infos... For the members issue i try to get an alt into the corp tonight to let that error re-occur. mayxbe the debug here already helps you to figure the issues.

2015-09-14 21:22:40,400 [INFO ] ecm.plugins.industry.views - Initialized item groups (took 0.16 sec.)
2015-09-14 21:23:13,090 [INFO ] ecm.apps.hr.tasks.members.tracking - fetching /corp/MemberTracking.xml.aspx...
2015-09-14 21:23:13,271 [DEBUG] ecm.apps.hr.tasks.members.tracking - current time : 2015-09-14 19:23:12+00:00
2015-09-14 21:23:13,271 [DEBUG] ecm.apps.hr.tasks.members.tracking - cached util : 2015-09-14 20:34:36+00:00
2015-09-14 21:23:13,271 [DEBUG] ecm.apps.hr.tasks.members.tracking - parsing api response...
2015-09-14 21:23:13,330 [DEBUG] ecm.apps.hr.tasks.members.tracking - RESIGNED MEMBERS:
2015-09-14 21:23:13,330 [DEBUG] ecm.apps.hr.tasks.members.tracking - (none)
2015-09-14 21:23:13,330 [DEBUG] ecm.apps.hr.tasks.members.tracking - NEW MEMBERS:
2015-09-14 21:23:13,330 [DEBUG] ecm.apps.hr.tasks.members.tracking - (none)
2015-09-14 21:23:13,330 [INFO ] ecm.apps.hr.tasks.members.tracking - 10 members parsed, 0 changes since last scan
2015-09-14 21:23:13,375 [INFO ] ecm.apps.hr.tasks.members.security - fetching /corp/MemberSecurity.xml.aspx...
2015-09-14 21:23:13,560 [DEBUG] ecm.apps.hr.tasks.members.security - current time : 2015-09-14 19:23:12+00:00
2015-09-14 21:23:13,561 [DEBUG] ecm.apps.hr.tasks.members.security - cached util : 2015-09-14 20:20:12+00:00
2015-09-14 21:23:13,561 [DEBUG] ecm.apps.hr.tasks.members.security - parsing api response...
2015-09-14 21:23:13,586 [ERROR] ecm.apps.scheduler.models -
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/ecm/apps/scheduler/models.py", line 120, in run
func(*args)
File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/members/init.py", line 26, in update
security.update()
File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 223, in inner
return func(args, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/members/security.py", line 84, in update
newTitles.update(parseOneMemberTitles(member, my_corp))
File "/usr/local/lib/python2.7/dist-packages/ecm/apps/hr/tasks/members/security.py", line 122, in parseOneMemberTitles
title = Title.objects.get(corp=my_corp, titleID=t.titleID)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 143, in get
return self.get_query_set().get(args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 404, in get
self.model._meta.object_name)
DoesNotExist: Title matching query does not exist.

**Comment by Dharr-Guartonzec** [comment] 2015-09-15 09:11
Upgrade done:

# pip install git+https://github.com/evecm/ecm --upgrade
/usr/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.0.3, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting git+https://github.com/evecm/ecm
    100% |ââââââââââââââââââââââââââââââââ| 462kB 593kB/s
Requirement already up-to-date: django<=1.5.7 in /usr/lib/python2.7/site-packages (from ecm==2.2.4.1)   88% |âââââââââââââââââââââââââââââ
Requirement already up-to-date: pytz in /usr/lib/python2.7/site-packages (from ecm==2.2.4.1)
Requirement already up-to-date: pycrypto in /usr/lib64/python2.7/site-packages (from ecm==2.2.4.1)
Requirement already up-to-date: six>=1.2.0 in /usr/lib/python2.7/site-packages (from django-simple-captcha>=0.3->ecm==2.2.4.1)ââââ
Requirement already up-to-date: django-appconf>=0.4 in /usr/lib/python2.7/site-packages (from django-compressor>=1.1.2->ecm==2.2.4.1)
Installing collected packages: setuptools, ecm
  Found existing installation: setuptools 18.2
    Uninstalling setuptools-18.2:
      Successfully uninstalled setuptools-18.2
  Found existing installation: ecm 2.2.3.1
    Uninstalling ecm-2.2.3.1:
      Successfully uninstalled ecm-2.2.3.1
  Running setup.py install for ecm
Successfully installed ecm-2.2.4.1 setuptools-18.3.1
#

**Comment by Dharr-Guartonzec** [comment] 2015-09-15 09:18
After the Update the error with the corp assets was gone after i ran the task manually. weird.

**Comment by Dharr-Guartonzec** [comment] 2015-09-17 10:19
Here we go... 2 new members joined and the error is back:


2015-09-17 08:50:02,164 [INFO ] ecm.apps.hr.tasks.titles - fetching /corp/Titles.xml.aspx...
2015-09-17 08:50:02,387 [DEBUG] ecm.apps.hr.tasks.titles - current time : 2015-09-17 08:50:08+00:00
2015-09-17 08:50:02,387 [DEBUG] ecm.apps.hr.tasks.titles - cached util : 2015-09-17 09:47:08+00:00
2015-09-17 08:50:02,387 [DEBUG] ecm.apps.hr.tasks.titles - parsing api response...
2015-09-17 08:50:02,771 [DEBUG] ecm.apps.hr.tasks.titles - REMOVED ROLES TO TITLES:
2015-09-17 08:50:02,771 [DEBUG] ecm.apps.hr.tasks.titles - (none)
2015-09-17 08:50:02,771 [DEBUG] ecm.apps.hr.tasks.titles - ADDED ROLES TO TITLES:
2015-09-17 08:50:02,771 [DEBUG] ecm.apps.hr.tasks.titles - (none)
2015-09-17 08:50:03,522 [INFO ] ecm.apps.hr.tasks.titles - 144 roles in titles parsed, 0 changes since last scan
2015-09-17 08:50:03,557 [INFO ] ecm.apps.hr.tasks.users - Updating user accesses from their in-game roles...
2015-09-17 08:50:03,613 [INFO ] ecm.apps.hr.tasks.users - User accesses updated
2015-09-17 09:20:02,242 [INFO ] ecm.apps.hr.tasks.members.tracking - fetching /corp/MemberTracking.xml.aspx...
2015-09-17 09:20:02,444 [DEBUG] ecm.apps.hr.tasks.members.tracking - current time : 2015-09-17 09:20:08+00:00
2015-09-17 09:20:02,444 [DEBUG] ecm.apps.hr.tasks.members.tracking - cached util : 2015-09-17 13:11:37+00:00
2015-09-17 09:20:02,444 [DEBUG] ecm.apps.hr.tasks.members.tracking - parsing api response...
2015-09-17 09:20:02,765 [DEBUG] ecm.apps.hr.tasks.members.tracking - RESIGNED MEMBERS:
2015-09-17 09:20:02,766 [DEBUG] ecm.apps.hr.tasks.members.tracking - (none)
2015-09-17 09:20:02,766 [DEBUG] ecm.apps.hr.tasks.members.tracking - NEW MEMBERS:
2015-09-17 09:20:02,766 [DEBUG] ecm.apps.hr.tasks.members.tracking - (none)
2015-09-17 09:20:02,766 [INFO ] ecm.apps.hr.tasks.members.tracking - 48 members parsed, 0 changes since last scan
2015-09-17 09:20:02,940 [INFO ] ecm.apps.hr.tasks.members.security - fetching /corp/MemberSecurity.xml.aspx...
2015-09-17 09:20:03,552 [DEBUG] ecm.apps.hr.tasks.members.security - current time : 2015-09-17 09:20:09+00:00
2015-09-17 09:20:03,552 [DEBUG] ecm.apps.hr.tasks.members.security - cached util : 2015-09-17 10:16:31+00:00
2015-09-17 09:20:03,552 [DEBUG] ecm.apps.hr.tasks.members.security - parsing api response...
2015-09-17 09:20:03,896 [DEBUG] ecm.apps.hr.tasks.members.security - REMOVED ROLES:
2015-09-17 09:20:03,897 [DEBUG] ecm.apps.hr.tasks.members.security - (none)
2015-09-17 09:20:03,897 [DEBUG] ecm.apps.hr.tasks.members.security - ADDED ROLES:
2015-09-17 09:20:03,897 [DEBUG] ecm.apps.hr.tasks.members.security - (none)
2015-09-17 09:20:03,898 [DEBUG] ecm.apps.hr.tasks.members.security - REMOVED TITLES:
2015-09-17 09:20:03,898 [DEBUG] ecm.apps.hr.tasks.members.security - (none)
2015-09-17 09:20:03,898 [DEBUG] ecm.apps.hr.tasks.members.security - ADDED TITLES:
2015-09-17 09:20:03,901 [DEBUG] ecm.apps.hr.tasks.members.security - + jenan Hyswa is Fleet Access
2015-09-17 09:20:03,903 [DEBUG] ecm.apps.hr.tasks.members.security - + Benji Bobbb is Public Access
2015-09-17 09:20:03,905 [DEBUG] ecm.apps.hr.tasks.members.security - + Benji Bobbb is Rental Wallet
2015-09-17 09:20:03,907 [DEBUG] ecm.apps.hr.tasks.members.security - + Benji Bobbb is Fleet Access
2015-09-17 09:20:03,910 [DEBUG] ecm.apps.hr.tasks.members.security - + jenan Hyswa is Rental Wallet
2015-09-17 09:20:03,912 [DEBUG] ecm.apps.hr.tasks.members.security - + jenan Hyswa is Public Access
2015-09-17 09:20:03,924 [ERROR] ecm.apps.scheduler.models -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ecm/apps/scheduler/models.py", line 120, in run
    func(**args)
  File "/usr/lib/python2.7/site-packages/ecm/apps/hr/tasks/members/__init__.py", line 26, in update
    security.update()
  File "/usr/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ecm/apps/hr/tasks/members/security.py", line 90, in update
    titleDiffs = storeTitles(oldTitles, newTitles, currentTime)
  File "/usr/lib/python2.7/site-packages/ecm/apps/hr/tasks/members/security.py", line 212, in storeTitles
    d.save()
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 546, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python2.7/site-packages/django/db/models/base.py", line 650, in save_base
    result = manager._insert([self], fields=fields, return_id=update_pk, using=using, raw=raw)
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 215, in _insert
    return insert_query(self.model, objs, fields, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 1675, in insert_query
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 943, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
Warning: Field 'id' doesn't have a default value

**Comment by ggrog** [comment] 2015-09-17 16:03
Thanks!  I think I have enough info for now.

**Comment by ggrog** [comment] 2015-09-17 21:34
### To summarize:

1. There was a bug where titles with duplicate names would fail, causing this error: https://github.com/evecm/ecm/issues/14#issuecomment-140182870  Resolved with 065fd9b.

2. The other errors in this issue `Warning: Field 'id' doesn't have a default value` are typically harmless.  However, if you have `debug = true` in your `settings.ini` Django will promote these MySQL warnings into errors.  Fix the warning with `debug = false` in `settings.ini`.  Also the warning is suppressed for ECM 2.2.4.2 with dcdeee8.  (Ref: https://code.djangoproject.com/ticket/23871)  This may help too http://old.webit.ca/2012/01/field-id-doesnt-have-a-default-value/.  I was never able to reproduce this.

Will close upon confirmation that the commit works.

**Comment by Dharr-Guartonzec** [comment] 2015-09-18 10:19
This  works for me! \o/

**Closed** 2015-09-18 14:49 UTC
